name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: read_tag
        name: Read Dockerfile tag
        run: |
          echo -n "NETBOX_VERSION=" >> $GITHUB_OUTPUT
          cat Dockerfile | grep FROM | head -n 1 | grep -Po '(?<=:).*$' >> $GITHUB_OUTPUT
      - name: Read Dockerfile tag result
        run: |
          echo "NETBOX_VERSION: ${{ steps.read_tag.outputs.NETBOX_VERSION }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@5964de0df58d5ad28b04d8fe2e6b80ad47105b91 # v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        name: Docker login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ steps.read_tag.outputs.NETBOX_VERSION }}
            type=sha,format=long
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}

      - name: Build the Docker image
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build And Push the Docker image
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
